# Generated by Django 5.1.1 on 2024-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Evenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("affiche", models.IntegerField(default=0)),
                ("nom", models.CharField(max_length=50)),
                ("lien_internet", models.URLField()),
                ("adresse", models.CharField(max_length=200)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                ("type_event", models.CharField(max_length=100)),
                ("enseigne", models.CharField(max_length=100)),
                ("lien_logo", models.URLField()),
            ],
        ),
    ]
