# Generated by Django 5.1.1 on 2024-10-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AjoutEvenement",
            "0002_alter_evenement_adresse_alter_evenement_affiche_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evenement",
            name="affiche",
        ),
        migrations.RemoveField(
            model_name="evenement",
            name="type_event",
        ),
        migrations.AddField(
            model_name="evenement",
            name="commentaire",
            field=models.TextField(default="Pas de commentaire"),
        ),
        migrations.AddField(
            model_name="evenement",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("Film", "Film"),
                    ("Compétition", "Compétition"),
                    ("Rassemblement", "Rassemblement"),
                    ("Contest", "Contest"),
                    ("Autre", "Autre"),
                ],
                default="Film",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="evenement",
            name="adresse",
            field=models.CharField(
                help_text="(Vérifier l'adresse sur <a href='https://www.openstreetmap.org/'>OpenStreetMap</a>)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="enseigne",
            field=models.CharField(
                choices=[
                    ("Autre", "Autre"),
                    ("Arkose", "Arkose"),
                    ("climbup", "Climb'Up"),
                    ("FFME", "FFME"),
                    ("Blocout", "Bloc'Out"),
                    ("FFME", "FFME"),
                    ("IFSC", "IFSC"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="lien_internet",
            field=models.URLField(help_text="(www.MonEvenement.com)"),
        ),
        migrations.AlterField(
            model_name="evenement",
            name="nom",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
