# Generated by Django 5.1.1 on 2024-10-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AjoutEvenement",
            "0003_remove_evenement_affiche_remove_evenement_type_event_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="type_evenement",
            field=models.CharField(
                choices=[
                    ("Film", "Film"),
                    ("Compétition", "Compétition"),
                    ("Rassemblement", "Rassemblement"),
                    ("Contest", "Contest"),
                    ("Autre", "Autre"),
                ],
                default="Autre",
                max_length=50,
            ),
        ),
    ]
