# Generated by Django 5.1.1 on 2024-10-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "AjoutEvenement",
            "0005_remove_evenement_lien_internet_evenement_lien_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="evenement",
            name="lien_logo",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
